train_introvae:
  args:
    dataset: 'cifar10'
    test: 'test'
  test:
    test


train_autoencoder:
  args:
    num_gpus: 1
  start:
    name: "do_train"
    dataset_name: "imagenet"
    IMS_PER_BATCH: 32
    ASPECT_RATIO_GROUPING: false
    NUM_WORKERS: 0
    dataset_mapper:
      name: "ImageNetDatasetMapper"
      img_size: 256
    max_epoch: 1000
    checkpoint_period: "10*iter_every_epoch"
  trainer:
    name: 'AutoEncoderTrainer'
    ngpu: 1
  encoder:
    name: "Encoder"
    ndf: 64
    padding_type: "reflect"
    use_dropout: false
    use_bias: false
#    nemb: 512
#    nemb: 128
#    nemb: 1024
    nemb: 256
    embedding: "sphere"
  decoder:
    name: "Decoder"
#    name: "DecoderBilinear"
#    nemb: 512
#    nemb: 128
#    nemb: 1024
    nemb: 256
    ngf: 64
    padding_type: "reflect"
    use_dropout: false
    use_bias: false
    nc: 3
  optimizer:
    lr: 0.0002
    beta1: 0
    beta2: 0.999


train_autoencoder_conv:
  base:
    - train_autoencoder
  encoder:
    overwrite: false
    name: "Encoder_conv"
    embedding: "normal"
    output_dim: 1
  decoder:
    overwrite: false
    name: "Decoder_conv"
    input_dim: 1

train_AEGAN_acai:
  base:
    - train_autoencoder
  start:
    IMS_PER_BATCH: 64
  trainer:
    name: 'AEGAN_acaiTrainer'
    reg: 0.2
    ngpu: 4
    updates_d: 5
    updates_D: 5
    noise: sphere
  encoder:
    overwrite: false
    name: "Encoder_conv"
    emb_channel: 1
  decoder:
    overwrite: false
    name: "Decoder_conv"
    emb_channel: 1
  netd:
    name: "netd"
    ndf: 64
    padding_type: "reflect"
    use_dropout: false
    use_bias: false
    nc: 3
  netD:
    name: "netD"
    ndf: 64
    emb_channel: 1
    padding_type: "reflect"
    use_dropout: false
    use_bias: false
  netg:
    name: "netg"
    ngf: 64
    padding_type: "reflect"
    use_dropout: false
    use_bias: false
    emb_channel: 1
    embedding: "sphere"
